name: Build Custom Injector

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Compile Injector.cpp
      run: |
        cl.exe /EHsc /O2 /MT injector.cpp /link user32.lib /OUT:QzWx3km.exe

    - name: Upload Injector Executable
      uses: actions/upload-artifact@v4
      with:
        name: StandChillow_Injector
        path: StandChillow_Injector.exe
